# Generated by Django 3.1.7 on 2021-04-20 11:51

from django.db import migrations


def create_public_group(apps, schema_editor):
    """Make public group after auth migrations.

    """
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    perm_project_view = Permission.objects.get(codename='projects.view_project')
    group_public = Group.objects.get(name='public')
    if group_public is None:
        group_public = Group.objects.create(name='public')
    group_public.permissions


def delete_public_group(apps, schema_editor):
    """Delete public group in migrations rollback.

    """
    Group = apps.get_model('auth', 'Group')
    group_public = Group.objects.get(name='public')
    if group_public is not None:
        group_public.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_public_group)
    ]
