# Generated by Django 3.1.7 on 2021-03-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_auto_20210322_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=80, verbose_name='Project name')),
                ('description', models.CharField(max_length=400, verbose_name='Description')),
                ('budget', models.FloatField(verbose_name='Budget')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('closed', models.BooleanField(verbose_name='Closed')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=80, verbose_name='Task name')),
                ('description', models.CharField(max_length=400, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('complete_date', models.DateTimeField(verbose_name='Complete date')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_author', to='employees.employee', verbose_name='Author')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_executor', to='employees.employee', verbose_name='Executor')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='Project')),
            ],
        ),
    ]
