# Generated by Django 3.1.7 on 2021-03-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210324_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Finished'), ('processed', 'Processed')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
