# Generated by Django 3.1.7 on 2021-03-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210325_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Finished'), ('in_progress', 'In progress')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
