# Generated by Django 3.1.7 on 2021-04-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_home', 'Can view home page')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
