# Generated by Django 3.1.7 on 2021-04-20 11:51

from django.db import migrations


def create_public_group(apps, schema_editor):
    """Make public group after auth migrations.

    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name='public')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_public_group)
    ]
