# Generated by Django 3.1.7 on 2021-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Firstname')),
                ('middlename', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middlename')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
            ],
        ),
    ]
