# Generated by Django 3.1.7 on 2021-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Middlename'),
        ),
    ]
