# Generated by Django 3.1.7 on 2021-03-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210322_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Middlename'),
        ),
    ]
