# Generated by Django 3.1.7 on 2021-03-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20210324_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Surname'),
        ),
    ]
