# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7, 3.8, 3.9, 3.10.0 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y gettext
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup localization
      run: |
        cd brigadier
        python manage.py compilemessages
    - name: Test with unittest
      run: |
        cd brigadier
        coverage run --source='.' manage.py test --verbosity=2
        coverage xml -o coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./brigadier/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
    - name: Check if coverage under 100
      run: |
        cd brigadier
        coverage report --fail-under=100